# Generated by Django 5.1.1 on 2024-09-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmodel',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images'),
        ),
    ]
