# Generated by Django 5.1.1 on 2024-09-13 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_adminmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='accounts/images', verbose_name='Profile Image')),
                ('phone', models.CharField(help_text='Enter phone number with country code', max_length=16, verbose_name='Phone Number')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Enter monthly salary', max_digits=10, verbose_name='Salary')),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('manager', 'Manager')], default='cashier', max_length=10, verbose_name='Job Role')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('address', models.CharField(help_text='Enter full address', max_length=300, verbose_name='Address')),
                ('additional_info', models.TextField(blank=True, help_text='Optional additional information', null=True, verbose_name='Additional Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='accounts.adminmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['user__first_name'],
            },
        ),
    ]
