# Generated by Django 5.1.1 on 2024-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminmodel_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, help_text='Enter full address', max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter phone number with country code', max_length=16, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('manager', 'Manager')], default='cashier', max_length=20, verbose_name='Job Role'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter monthly salary', max_digits=10, null=True, verbose_name='Salary'),
        ),
    ]
