# Generated by Django 5.1.1 on 2024-09-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_gender_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.adminmodel'),
        ),
    ]
